|                |   |
:----------------|---|
| **Nombre**     | Valeria Guzmán Galván  |
| **Fecha**      | 23/04/2026  |
| **Expediente** | 756902  |

In [1]:
import pandas as pd

In [2]:
data = {
    "Sexo": ["H","M","H","H","H","H","H","H","H","M","M","H","H","H","H","H"],
    "Edad": [21,19,21,19,20,21,22,21,19,21,19,21,20,20,19,19],
    "Estatura": [1.73,1.62,1.73,1.69,1.75,1.80,1.70,1.75,1.66,1.64,1.62,1.85,1.75,1.66,1.70,1.64]
}

In [3]:
df = pd.DataFrame(data)
df

   Sexo  Edad  Estatura
0     H    21      1.73
1     M    19      1.62
2     H    21      1.73
3     H    19      1.69
4     H    20      1.75
5     H    21      1.80
6     H    22      1.70
7     H    21      1.75
8     H    19      1.66
9     M    21      1.64
10    M    19      1.62
11    H    21      1.85
12    H    20      1.75
13    H    20      1.66
14    H    19      1.70
15    H    19      1.64

**Filtros para el promedio de la estatura**

1. Hombre mayor o igual a 21 años

2. Hombre menor a 21 años

3. Mujer igual a 19 años

4. Mujer igual a 21 años

In [4]:
filtro1 = df[(df["Sexo"] == "H") & (df["Edad"] >= 21)]
promedio1 = filtro1["Estatura"].mean()
print(promedio1)

1.76

In [5]:
filtro2 = df[(df["Sexo"] == "H") & (df["Edad"] < 21)]
promedio2 = filtro2["Estatura"].mean()
print(promedio2)

1.6928571428571428

In [6]:
filtro3 = df[(df["Sexo"] == "M") & (df["Edad"] == 19)]
promedio3 = filtro3["Estatura"].mean()
print(promedio3)

1.62

In [7]:
filtro4 = df[(df["Sexo"] == "M") & (df["Edad"] == 21)]
promedio4 = filtro4["Estatura"].mean()
print(promedio4)

1.64

## Actividad

* Tomar advertising.csv y hacer una regresion lineal simple
* Calcular R^2 de (1)
* Usar arbol de desicion para regresion sobre el mismo data set
* Calcular R^2 de (3)
* Repetir (1-4) con train-test split 50/50

In [8]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [9]:
from google.colab import files
uploaded = files.upload()

Saving Advertising.csv to Advertising.csv

In [10]:
obj = pd.read_csv ("Advertising.csv")
obj.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

### Regresión lineal simple

In [11]:
X = obj [["TV", "radio", "newspaper"]]
y = obj ["sales"]

In [12]:
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [13]:
print(lr.coef_)
print(lr.intercept_)

[ 0.04576465  0.18853002 -0.00103749]
2.938889369459412

In [14]:
r2 = lr.score(X, y)
r2

0.8972106381789522

### Árbol de Decisión

In [15]:
tree = DecisionTreeRegressor(random_state=42)
tree.fit (X,y)

DecisionTreeRegressor(random_state=42)

In [16]:
r2_tree = tree.score(X,y)
r2_tree

1.0

### Train-test split 50/50

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

In [18]:
# Train-test split con Regresión Lineal
lr.fit(X_train, y_train)

r2_train_tree = lr.score(X_train, y_train)
r2_test_tree = lr.score(X_test, y_test)

print("R2 en Train:", r2_train_tree)
print("R2 en Test:", r2_test_tree)

R2 en Train: 0.9042613648908893
R2 en Test: 0.8721004816045135

In [19]:
# Train-test split con Árbol de Decisión
tree.fit(X_train, y_train)

r2_train_tree = tree.score(X_train, y_train)
r2_test_tree = tree.score(X_test, y_test)
print("R2 en Train Tree:", r2_train_tree)
print("R2 en Test Tree:", r2_test_tree)

R2 en Train Tree: 1.0
R2 en Test Tree: 0.9344975035059896